name: Test

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"

env:
  PYTEST_ADDOPTS: "--color=yes"

# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Set permissions at the job level.
permissions: {}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Build and Check Package
      uses: hynek/build-and-inspect-python-package@v1.5.4

  build:
    needs: [package]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        name: [
          "windows-py310",
          "windows-py311",
          "windows-py312",

          "ubuntu-py310",
          "ubuntu-py311",
          "ubuntu-py312",
          "ubuntu-pypy3",

          "macos-py310",
          "macos-py312",

          "doctesting",
          "plugins",
        ]

        include:
          - name: "windows-py310"
            python: "3.10"
            os: windows-latest
            tox_env: "py310-xdist"
          - name: "windows-py311"
            python: "3.11"
            os: windows-latest
            tox_env: "py311"
          - name: "windows-py312"
            python: "3.12-dev"
            os: windows-latest
            tox_env: "py312"

          - name: "ubuntu-py310"
            python: "3.10"
            os: ubuntu-latest
            tox_env: "py310-xdist"
          - name: "ubuntu-py311"
            python: "3.11"
            os: ubuntu-latest
            tox_env: "py311"
            use_coverage: true
          - name: "ubuntu-py312"
            python: "3.12-dev"
            os: ubuntu-latest
            tox_env: "py312"
            use_coverage: true
          - name: "ubuntu-pypy3"
            python: "pypy-3.9"
            os: ubuntu-latest
            tox_env: "pypy3-xdist"

          - name: "macos-py310"
            python: "3.10"
            os: macos-latest
            tox_env: "py310-xdist"
          - name: "macos-py312"
            python: "3.12-dev"
            os: macos-latest
            tox_env: "py312-xdist"

          - name: "plugins"
            python: "3.12"
            os: ubuntu-latest
            tox_env: "plugins"

          - name: "doctesting"
            python: "3.10"
            os: ubuntu-latest
            tox_env: "doctesting"
            use_coverage: true

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Download Package
      uses: actions/download-artifact@v3
      with:
        name: Packages
        path: dist

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        check-latest: ${{ endsWith(matrix.python, '-dev') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.txt
        python -m pip install -e .

    - name: Test with coverage
      if: "matrix.use_coverage"
      shell: bash
      run: pytest --cov=./ --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
